### ISSUE TITLE
兄弟，你要抄能把我的站点统计删了吗？

### ISSUE THREAD

**Issue by showzeng** [nlls1990/nlls1990.github.io#1]
看到你直接这样抄袭，连个 star 也不想给？这个博客都是自己写的，整体界面有借鉴但也都是自己设计的，看到你这样，连个出处也不注明，我很伤心。麻烦你把我的站点统计删了，别让我看见行吗？

**Comment by nlls1990** [comment]
抱歉, 初学前端, 参考你的样式先改改, 平时没空, 只有周末再改了

**Comment by showzeng** [comment]
好的，谢谢理解！
